tdengine:
  path: localhost
  port: 6041
  username: root
  password: taosdata
  db-name: tdengine
  log-mode: error
ali-amqp-cred:
  ali-amqp-host: iot-amqp.cn-shanghai.aliyuncs.com
  ali-amqp-port: 5671
  aliyun-uid:
  iot-instance-id:
  access-key:
  access-secret:
  consumer-group-id:
  client-id:
cordons:
  bridge-deck-temp-1: 99999
  bridge-deck-temp-2: 99999
  ambient-temp-1: 99999
  ambient-humidity-1: 99999
  ambient-temp-2: 99999
  ambient-humidity-2: 99999
  deflection-1: 99999
  deflection-2: 99999
  cable-tension-1: 99999
  cable-tension-2: 99999
  static-strain-temp-1: 99999
  static-strain-temp-2: 99999
  static-strain-value-1: 99999
  static-strain-value-2: 99999
  seismic-x-value-1: 99999
  seismic-x-value-2: 99999
  seismic-z-value-1: 99999
  seismic-z-value-2: 99999
  driveway-weight-1: 99999
  driveway-weight-2: 99999
  driveway-speed-1: 99999
  driveway-speed-2: 99999
  alarm-contacts:
  alarm-sms-template-id: